services:
  app:
    build: .
    depends_on:
      - database
      - redis
    volumes:
      - .:/app
      - storage_data:/var/www/app_storage
      - gems_volume:/gems:cached
    env_file:
      - .env.web
      - .env.database
      - .env.pg
    ports:
      - 3500:3000
    tty: true

  redis:
    image: redis
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data

  database:
    image: postgres:16.1
    env_file:
      - .env.database
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env.pg
    ports:
      - 7100:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin


volumes:
  db_data:
  redis_data:
  pgadmin-data:
  storage_data:
  gems_volume: